
data_source datasource_n:
     type: snowflake
     username: NEELABH108
     password: Expleo#2024
     account: ge83479.central-india.azure
     database: NEW_DB
     schema: NEW_SCHEMA
     warehouse: COMPUTE_WH
     role: ACCOUNTADMIN
soda_cloud:
     host: cloud.us.soda.io
     api_key_id: a0933b60-03a2-4db6-818f-b5b0c12a4916
     api_key_secret: dmv6ajt8LRo7Svmb9HLIU-PFRletfYxvf3FrYGdeEgHJ_x39TLE6HA
