data_source dbsource1:
     type: snowflake
     username: NEELABH02
     password: Welcome@123
     account: sn90446.europe-west4.gcp
     database: MY_DB
     schema: MY_SCHEMA
     warehouse: COMPUTE_WH
     role: ACCOUNTADMIN
soda_cloud:
     host: cloud.soda.io
     api_key_id: 4e80d0ad-b883-495f-b94d-6b67bb913063
     api_key_secret: FbU2KDam1uYqiMuUvdlmKJ-W5xwVFW9qsgjYD3LvbsghrCO3Tz-10Q
# dbt_cloud:
#      account_id: 70403103935295
#      api_token: dbtc_oofe0zwNt3Ho7sbSkJWc2mpQ35YWDuOYDxISx8drz5boA83B3Y
#      access_url: https://hd377.us1.dbt.com/
